version: '3'

services:
  sol-compile:
    build: ./
    command: build:watch
    volumes:
      - ./contracts:/app/contracts:delegated
      - ./artifacts:/app/artifacts:cached

  jest:
    build: ./
    command: test:watch
    volumes:
      - ./contracts:/app/contracts:delegated
      - ./artifacts:/app/artifacts:delegated
      - ./.babelrc:/app/.babelrc:delegated
      - ./compiler.json:/app/compiler.json:delegated
    depends_on:
      - ganache

  ganache:
    image: trufflesuite/ganache-cli:latest
    command: ganache-cli -m 'candy maple cake sugar pudding cream honey rich smooth crumble sweet treat'

  zok:
    image: kartheek14/zokrates_dev:081419
    volumes:
      - ./zok/code:/home/zokrates/zok_code
      - ./zok/output:/home/zokrates/output
