version: '3'

services:
  radish-api-supplier1:
    build:
      context: ./radish-api/
      dockerfile: dev.Dockerfile
    command: npm run dev
    restart: on-failure
    volumes:
      - ./radish-api/dist:/app/dist:delegated
      - ./radish-api/package.json:/app/package.json:delegated
      - ./config/keystore/supplier1.eth:/keystore/account.eth
      - ./config/config-supplier1.json:/app/config/default.json
      - ./artifacts:/app/artifacts:delegated      
    depends_on:
      - mongo-supplier1
    environment:
      VIRTUAL_HOST: radish-api-supplier1.docker
      MONGO_URL: mongodb://mongo-supplier1
      MONGO_DB_NAME: 'radish34'
      MONGO_CONNECTION_RETRIES: 5
    ports:
      - 8002:8001

  radish-api-supplier2:
    build:
      context: ./radish-api/
      dockerfile: dev.Dockerfile
    command: npm run dev
    restart: on-failure
    volumes:
      - ./radish-api/dist:/app/dist:delegated
      - ./radish-api/package.json:/app/package.json:delegated
      - ./config/keystore/supplier2.eth:/keystore/account.eth
      - ./config/config-supplier2.json:/app/config/default.json
      - ./artifacts:/app/artifacts:delegated      
    depends_on:
      - mongo-supplier2
    environment:
      VIRTUAL_HOST: radish-api-supplier2.docker
      MONGO_URL: mongodb://mongo-supplier2
      MONGO_DB_NAME: 'radish34'
      MONGO_CONNECTION_RETRIES: 5
    ports:
      - 8003:8001

  radish-api-supplier3:
    build:
      context: ./radish-api/
      dockerfile: dev.Dockerfile
    command: npm run dev
    restart: on-failure
    volumes:
      - ./radish-api/dist:/app/dist:delegated
      - ./radish-api/package.json:/app/package.json:delegated
      - ./config/keystore/supplier3.eth:/keystore/account.eth
      - ./config/config-supplier3.json:/app/config/default.json
      - ./artifacts:/app/artifacts:delegated      
    depends_on:
      - mongo-supplier3
    environment:
      VIRTUAL_HOST: radish-api-supplier3.docker
      MONGO_URL: mongodb://mongo-supplier3
      MONGO_DB_NAME: 'radish34'
      MONGO_CONNECTION_RETRIES: 5
    ports:
      - 8004:8001
      
  mongo-supplier1:
    image: mongo:latest
    container_name: mongo-supplier1
    volumes:
      - mongo-supplier1:/data/db
    logging:
      options:
        max-size: 10m

  mongo-supplier2:
    image: mongo:latest
    container_name: mongo-supplier2
    volumes:
      - mongo-supplier2:/data/db
    logging:
      options:
        max-size: 10m

  mongo-supplier3:
    image: mongo:latest
    container_name: mongo-supplier3
    volumes:
      - mongo-supplier3:/data/db
    logging:
      options:
        max-size: 10m
    networks:
      chainnet:
        ipv4_address: 172.25.0.125        

volumes:
  mongo-supplier1:
  mongo-supplier2:
  mongo-supplier3:

networks:
  chainnet:
    driver: bridge
    ipam:
      config:
      - subnet: 172.25.0.0/24
      