version: '3'

services:
  sol-compile:
    build: ./
    command: build:watch
    volumes:
      - ./contracts:/app/contracts:delegated
      - ./artifacts:/app/artifacts:cached

  jest:
    build: ./
    command: test:watch
    volumes:
      - ./contracts:/app/contracts:delegated
      - ./artifacts:/app/artifacts:delegated
      - ./.babelrc:/app/.babelrc:delegated
      - ./compiler.json:/app/compiler.json:delegated
    depends_on:
      - ganache

  ganache:
    image: trufflesuite/ganache-cli:latest
    command: ganache-cli -m 'candy maple cake sugar pudding cream honey rich smooth crumble sweet treat' --defaultBalanceEther 10000 --account="0x5aaa244692f54da4335a8553249b0db34316fbbc6ec353e1404cf77c415e59e8, 1000000000000000000000" --account="0x70441f8ed88f91416fbe21aa007357354e9bc30236211eda0022bdfb27beb227, 1000000000000000000000" --account="0x9ff4f711a85ed35d2cc66323abcd83f41e5981e0cd395800a262beb9a92b8abf, 1000000000000000000000" --account="0x77e701995d56e775bbb06559ece7d7352157106bbadc6aa5d8781c86c8d824bd, 1000000000000000000000" --networkId '333' --gasLimit 80000000000
    ports:
      - 8545:8545

  radish-zok:
    build:
      context: ./zok/
      dockerfile: dev.Dockerfile
    volumes:
      - ./zok/code:/app/code
      - ./zok/init.js:/app/init.js
      - ./zok/dist:/app/dist:delegated
    command: tail -F /dev/null
      
  radish34-ui:
    build:
      context: ./ui/
      dockerfile: dev.Dockerfile
    volumes:
      - ./ui/src:/app/src:delegated
      - ./ui/.env:/app/.env:delegated
      - ./ui/public/index.html:/app/public/index.html:delegated
      - ./ui/public/favicon.ico:/app/public/favicon.ico:delegated
      - ./ui/public/config.js:/app/public/config.js:delegated
      - ./ui/public/manifest.json:/app/public/manifest.json:delegated
      - ./ui/public/logo.svg:/app/public/logo.svg:delegated
      - ./ui/public/images:/app/public/images:delegated
    environment:
      VIRTUAL_HOST: radish34-ui.docker
    logging:
      options:
        max-size: 10m

  radish-api-buyer:
    build:
      context: ./radish-api/
      dockerfile: dev.Dockerfile
    command: npm run dev
    restart: on-failure
    volumes:
      - ./radish-api/dist:/app/dist:delegated
      - ./radish-api/package.json:/app/package.json:delegated
      - ./config/keystore/buyer.eth:/keystore/account.eth
      - ./config/config-buyerA.json:/app/config/default.json
      - ./artifacts:/app/artifacts:delegated
    depends_on:
      - radish-api-watch
      - mongo-buyer
      - ganache
    environment:
      VIRTUAL_HOST: radish-api-buyer.docker
      MONGO_URL: mongodb://mongo-buyer
      MONGO_DB_NAME: 'radish34'
      MONGO_CONNECTION_RETRIES: 5
    ports:
      - 8001:8001

  radish-api-supplier1:
    build:
      context: ./radish-api/
      dockerfile: dev.Dockerfile
    command: npm run dev
    restart: on-failure
    volumes:
      - ./radish-api/dist:/app/dist:delegated
      - ./radish-api/package.json:/app/package.json:delegated
      - ./config/keystore/supplier1.eth:/keystore/account.eth
      - ./config/config-supplier1.json:/app/config/default.json
      - ./artifacts:/app/artifacts:delegated      
    depends_on:
      - radish-api-watch
      - mongo-supplier1
      - ganache
    environment:
      VIRTUAL_HOST: radish-api-supplier1.docker
      MONGO_URL: mongodb://mongo-supplier1
      MONGO_DB_NAME: 'radish34'
      MONGO_CONNECTION_RETRIES: 5
    ports:
      - 8002:8001

  radish-api-supplier2:
    build:
      context: ./radish-api/
      dockerfile: dev.Dockerfile
    command: npm run dev
    restart: on-failure
    volumes:
      - ./radish-api/dist:/app/dist:delegated
      - ./radish-api/package.json:/app/package.json:delegated
      - ./config/keystore/supplier2.eth:/keystore/account.eth
      - ./config/config-supplier2.json:/app/config/default.json
      - ./artifacts:/app/artifacts:delegated      
    depends_on:
      - radish-api-watch
      - mongo-supplier2
      - ganache
    environment:
      VIRTUAL_HOST: radish-api-supplier2.docker
      MONGO_URL: mongodb://mongo-supplier2
      MONGO_DB_NAME: 'radish34'
      MONGO_CONNECTION_RETRIES: 5
    ports:
      - 8003:8001

  radish-api-supplier3:
    build:
      context: ./radish-api/
      dockerfile: dev.Dockerfile
    command: npm run dev
    restart: on-failure
    volumes:
      - ./radish-api/dist:/app/dist:delegated
      - ./radish-api/package.json:/app/package.json:delegated
      - ./config/keystore/supplier3.eth:/keystore/account.eth
      - ./config/config-supplier3.json:/app/config/default.json
      - ./artifacts:/app/artifacts:delegated      
    depends_on:
      - radish-api-watch
      - mongo-supplier3
      - ganache
    environment:
      VIRTUAL_HOST: radish-api-supplier3.docker
      MONGO_URL: mongodb://mongo-supplier3
      MONGO_DB_NAME: 'radish34'
      MONGO_CONNECTION_RETRIES: 5
    ports:
      - 8004:8001

  radish-api-watch:
    build:
      context: ./radish-api/
      dockerfile: dev.Dockerfile
    command: npm run build:watch
    volumes:
      - ./radish-api/src:/app/src:delegated
      - ./radish-api/dist:/app/dist:delegated
      - ./config/keystore:/keystore
      - ./config/config.json:/app/config/default.json
    logging:
      options:
        max-size: 10m

  mongo-buyer:
    image: mongo:latest
    container_name: mongo-buyer
    volumes:
      - mongo-buyer:/data/db
    logging:
      options:
        max-size: 10m
    ports:
      - 27017:27017
      
  mongo-supplier1:
    image: mongo:latest
    container_name: mongo-supplier1
    volumes:
      - mongo-supplier1:/data/db
    logging:
      options:
        max-size: 10m
    ports:
      - 27117:27017

  mongo-supplier2:
    image: mongo:latest
    container_name: mongo-supplier2
    volumes:
      - mongo-supplier2:/data/db
    logging:
      options:
        max-size: 10m
    ports:
      - 27217:27017

  mongo-supplier3:
    image: mongo:latest
    container_name: mongo-supplier3
    volumes:
      - mongo-supplier3:/data/db
    logging:
      options:
        max-size: 10m
    ports:
      - 27317:27017  

  mongo-seed:
    build: ./mongo-seed
    links:
      - mongo-buyer

volumes:
  mongo-buyer:
  mongo-supplier1:
  mongo-supplier2:
  mongo-supplier3:

networks:
  chainnet:
    driver: bridge
    ipam:
      config:
      - subnet: 172.25.0.0/24
      