version: '3'

services:
  sol-compile:
    build: ./
    command: build:watch
    volumes:
      - ./contracts:/app/contracts:delegated
      - ./artifacts:/app/artifacts:cached

  jest:
    build: ./
    command: test:watch
    volumes:
      - ./contracts:/app/contracts:delegated
      - ./artifacts:/app/artifacts:delegated
      - ./.babelrc:/app/.babelrc:delegated
      - ./compiler.json:/app/compiler.json:delegated
    depends_on:
      - ganache

  ganache:
    image: trufflesuite/ganache-cli:latest
    command: ganache-cli -m 'candy maple cake sugar pudding cream honey rich smooth crumble sweet treat'

  zok:
    image: kartheek14/zokrates_dev:081519
    volumes:
      - ./zok/code:/home/zokrates/zok_code
      - ./zok/output:/home/zokrates/output
      
  radish34-ui:
    build:
      context: ./ui/
      dockerfile: dev.Dockerfile
    volumes:
      - ./ui/src:/app/src:delegated
      - ./ui/.env:/app/.env:delegated
      - ./ui/public/index.html:/app/public/index.html:delegated
      - ./ui/public/favicon.ico:/app/public/favicon.ico:delegated
      - ./ui/public/manifest.json:/app/public/manifest.json:delegated
      - ./ui/public/logo.svg:/app/public/logo.svg:delegated
    environment:
      VIRTUAL_HOST: radish34-ui.docker
    logging:
      options:
        max-size: 10m

  radish-api:
    build:
      context: ./radish-api/
      dockerfile: dev.Dockerfile
    command: npm run dev
    restart: on-failure
    volumes:
      - ./radish-api/build:/app/build:delegated
      - ./radish-api/package.json:/app/package.json:delegated
    depends_on:
      - radish-api-watch
      - ganache
    environment:
      VIRTUAL_HOST: radish-api.docker

  radish-api-watch:
    build:
      context: ./radish-api/
      dockerfile: dev.Dockerfile
    command: npm run watch
    volumes:
      - ./radish-api/src:/app/src:delegated
      - ./radish-api/build:/app/build:delegated
      - ./radish-api/.babelrc:/app/.babelrc
    logging:
      options:
        max-size: 10m

  mongo:
    image: mongo:latest
    volumes:
      - mongo-volume:/data/db
    logging:
      options:
        max-size: 10m

  mongo-seed:
    build: ./mongo-seed
    links:
      - mongo

volumes:
  mongo-volume: {}

networks:
  chainnet:
    driver: bridge
    ipam:
      config:
      - subnet: 172.25.0.0/24
      