version: '3'

services:
  geth-bootnode:
    hostname: geth-bootnode
    container_name: geth-bootnode
    environment:
      - nodekeyhex=08f0e1dee5c1b4645f3331a566009e41a4514b6cd28656d63d0449ecf812812b #Needs to be fix, so that the miners know the resulting enode id
    build:
      context: ./
      dockerfile: ./bootnode/Dockerfile
    ports:
      - 30301:30301/udp
    networks:
      chainnet:
        ipv4_address: 172.25.0.101 # The miners need to know the IP address later on

  geth-dev-miner-1:
    hostname: geth-dev-miner-1
    depends_on:
      - geth-bootnode
    environment:
      - nodekeyhex=8eb666d3e8a42bfc7d9e829af60b6d9142d65bef1ecb5897622b4c3ef93377e2 # This sets the enode so light nodes can use static-nodes.json to add as peer
      - address=0x8cc5a1a0802db41db826c2fcb72423744338dcb0 # derived from the private key which is passed in the args
      - bootnodeId=76a8171707eca17647a47ca99ffd348927dfa60102792ea349a25d5192e61855be83b786e376276a306afcceea4ffd1c9c77e4370b417efc39f328a0d068004c #derived from the nodekeyhex of the bootnode
      - bootnodeIp=172.25.0.101
    ports:
      - 8544:8545/tcp
    build:
      context: ./
      dockerfile: ./miner/Dockerfile
      args:
        privatekey: df504d175ae63abf209bad9dda965310d99559620550e74521a6798a41215f46 # Please don't do something like this in production, okay?
        password: pass
    container_name: geth-miner-1
    volumes:
      - eth-data-1:/root/.ethash
    networks:
      chainnet:
        ipv4_address: 172.25.0.102 # The monitor needs to know this address

  geth-dev-miner-2:
    hostname: geth-dev-miner-2
    depends_on:
      - geth-bootnode
    environment:
      - nodekeyhex=8861389742e9ee2669855a4928a712cec0f275241a359647772df689840c3c6c # This sets the enode so light nodes can use static-nodes.json to add as peer
      - address=0x3590aca93338b0721966a8d0c96ebf2c4c87c544 # derived from the private key which is passed in the args
      - bootnodeId=76a8171707eca17647a47ca99ffd348927dfa60102792ea349a25d5192e61855be83b786e376276a306afcceea4ffd1c9c77e4370b417efc39f328a0d068004c #derived from the nodekeyhex of the bootnode
      - bootnodeIp=172.25.0.101
    ports:
      - 8542:8545/tcp
    build:
      context: ./
      dockerfile: ./miner/Dockerfile
      args:
        privatekey: bc5b578e0dcb2dbf98dd6e5fe62cb5a28b84a55e15fc112d4ca88e1f62bd7c35
        password: word
    container_name: geth-miner-2
    volumes:
     - eth-data-2:/root/.ethash
    networks:
      chainnet:
        ipv4_address: 172.25.0.104

  geth-node-full-1:
     hostname: geth-node-full-1
     depends_on:
       - geth-dev-miner-1
     environment:
       - nodeType=full
       - address=0x3590aca93338b0721966a8d0c96ebf2c4c87c544 # derived from the private key which is passed in the args
       - bootnodeId=76a8171707eca17647a47ca99ffd348927dfa60102792ea349a25d5192e61855be83b786e376276a306afcceea4ffd1c9c77e4370b417efc39f328a0d068004c #derived from the nodekeyhex of the bootnode
       - bootnodeIp=172.25.0.101
     build:
       context: ./
       dockerfile: ./node/Dockerfile
       args:
         privatekey: bc5b578e0dcb2dbf98dd6e5fe62cb5a28b84a55e15fc112d4ca88e1f62bd7c35
         password: word
     container_name: geth-node-full-1
     ports:
       - 8545:8545
       - 8546:8546
     healthcheck:
       test: wget http://localhost:8545
       interval: 2s
       timeout: 5s
       retries: 30
     volumes:
      - eth-full-data-1:/root/.ethash
     networks:
       chainnet:
         ipv4_address: 172.25.0.110

  geth-node-full-2:
     hostname: geth-node-full-2
     depends_on:
       - geth-dev-miner-1
     environment:
       - nodeType=full
       - address=0x3590aca93338b0721966a8d0c96ebf2c4c87c544 # derived from the private key which is passed in the args
       - bootnodeId=76a8171707eca17647a47ca99ffd348927dfa60102792ea349a25d5192e61855be83b786e376276a306afcceea4ffd1c9c77e4370b417efc39f328a0d068004c # derived from the nodekeyhex of the bootnode
       - bootnodeIp=172.25.0.101
     build:
       context: ./
       dockerfile: ./node/Dockerfile
       args:
         privatekey: bc5b578e0dcb2dbf98dd6e5fe62cb5a28b84a55e15fc112d4ca88e1f62bd7c35
         password: word
     container_name: geth-node-full-2
     ports:
       - 8547:8545
       - 8548:8546
     healthcheck:
       test: wget http://localhost:8545
       interval: 2s
       timeout: 5s
       retries: 30
     volumes:
      - eth-full-data-2:/root/.ethash
     networks:
       chainnet:
         ipv4_address: 172.25.0.111

  geth-node-full-3:
     hostname: geth-node-full-3
     depends_on:
       - geth-dev-miner-1
     environment:
       - nodeType=full
       - address=0x3590aca93338b0721966a8d0c96ebf2c4c87c544 # derived from the private key which is passed in the args
       - bootnodeId=76a8171707eca17647a47ca99ffd348927dfa60102792ea349a25d5192e61855be83b786e376276a306afcceea4ffd1c9c77e4370b417efc39f328a0d068004c # derived from the nodekeyhex of the bootnode
       - bootnodeIp=172.25.0.101
     build:
       context: ./
       dockerfile: ./node/Dockerfile
       args:
         privatekey: bc5b578e0dcb2dbf98dd6e5fe62cb5a28b84a55e15fc112d4ca88e1f62bd7c35
         password: word
     container_name: geth-node-full-3
     ports:
       - 8549:8545
       - 8550:8546
     healthcheck:
       test: wget http://localhost:8545
       interval: 2s
       timeout: 5s
       retries: 30
     volumes:
      - eth-full-data-3:/root/.ethash
     networks:
       chainnet:
         ipv4_address: 172.25.0.112

  geth-node-light-1:
     hostname: geth-node-light-1
     depends_on:
       - geth-dev-miner-1
     environment:
       - nodeType=light
       - address=0x3590aca93338b0721966a8d0c96ebf2c4c87c544 # derived from the private key which is passed in the args
       - bootnodeId=76a8171707eca17647a47ca99ffd348927dfa60102792ea349a25d5192e61855be83b786e376276a306afcceea4ffd1c9c77e4370b417efc39f328a0d068004c # derived from the nodekeyhex of the bootnode
       - bootnodeIp=172.25.0.101
     build:
       context: ./
       dockerfile: ./node/Dockerfile
       args:
         privatekey: bc5b578e0dcb2dbf98dd6e5fe62cb5a28b84a55e15fc112d4ca88e1f62bd7c35
         password: word
     container_name: geth-node-light-1
     ports:
       - 8545:8545
       - 8546:8546
     healthcheck:
       test: wget http://localhost:8545
       interval: 2s
       timeout: 5s
       retries: 30
     volumes:
      - eth-light-data-1:/root/.ethash
     networks:
       chainnet:
         ipv4_address: 172.25.0.110
  
  geth-node-light-2:
     hostname: geth-node-light-2
     depends_on:
       - geth-dev-miner-1
     environment:
       - nodeType=light
       - address=0x3590aca93338b0721966a8d0c96ebf2c4c87c544 # derived from the private key which is passed in the args
       - bootnodeId=76a8171707eca17647a47ca99ffd348927dfa60102792ea349a25d5192e61855be83b786e376276a306afcceea4ffd1c9c77e4370b417efc39f328a0d068004c # derived from the nodekeyhex of the bootnode
       - bootnodeIp=172.25.0.101
     build:
       context: ./
       dockerfile: ./node/Dockerfile
       args:
         privatekey: bc5b578e0dcb2dbf98dd6e5fe62cb5a28b84a55e15fc112d4ca88e1f62bd7c35
         password: word
     container_name: geth-node-light-2
     ports:
       - 8547:8545
       - 8548:8546
     healthcheck:
       test: wget http://localhost:8545
       interval: 2s
       timeout: 5s
       retries: 30
     volumes:
      - eth-light-data-2:/root/.ethash
     networks:
       chainnet:
         ipv4_address: 172.25.0.111
  
  geth-node-light-3:
     hostname: geth-node-light-3
     depends_on:
       - geth-dev-miner-1
     environment:
       - nodeType=light
       - address=0x3590aca93338b0721966a8d0c96ebf2c4c87c544 # derived from the private key which is passed in the args
       - bootnodeId=76a8171707eca17647a47ca99ffd348927dfa60102792ea349a25d5192e61855be83b786e376276a306afcceea4ffd1c9c77e4370b417efc39f328a0d068004c # derived from the nodekeyhex of the bootnode
       - bootnodeIp=172.25.0.101
     build:
       context: ./
       dockerfile: ./node/Dockerfile
       args:
         privatekey: bc5b578e0dcb2dbf98dd6e5fe62cb5a28b84a55e15fc112d4ca88e1f62bd7c35
         password: word
     container_name: geth-node-light-3
     ports:
       - 8549:8545
       - 8550:8546
     healthcheck:
       test: wget http://localhost:8545
       interval: 2s
       timeout: 5s
       retries: 30
     volumes:
      - eth-light-data-3:/root/.ethash
     networks:
       chainnet:
         ipv4_address: 172.25.0.112

  geth-explorer:
    hostname: geth-explorer
    depends_on:
      - geth-dev-miner-2
    ports:
      - 8080:8080
    build:
      context: ./
      dockerfile: ./explorer/Dockerfile
    container_name: geth-explorer
    networks:
      chainnet:
        ipv4_address: 172.25.0.125

  mongo:
    image: mongo:latest
    container_name: mongo-db
    volumes:
      - radish-mongo:/data/db
    ports:
      - 27018:27017
    logging:
      options:
        max-size: 10m
    networks:
      chainnet:
        ipv4_address: 172.25.0.126

networks:
  chainnet:
    driver: bridge
    ipam:
      config:
      - subnet: 172.25.0.0/24

volumes:
  eth-data-1:
  eth-data-2:
  eth-light-data-1:
  eth-light-data-2:
  eth-light-data-3:
  eth-full-data-1:
  eth-full-data-2:
  eth-full-data-3:
  radish-mongo:
